language: node_js
node_js:
  - '8'

os:
 - osx

branches:
  only:
    - master

cache:
  directories:
  - node_modules
  - .vscode-test

git:
  depth: false
  quite: true

install:
  - yarn
script:
  - yarn ci
