language: node_js
node_js:
  - '7'

branches:
  only:
    - master

cache:
  directories:
  - node_modules

git:
  depth: false
  quite: true

install:
  - yarn
  - yarn vscode:prepublish
before_script:
  - yarn lint
script:
  - yarn test
